### ISSUE TITLE
Running dump.py produces error: "No such interface 're.frida.HostSession12' on object at path /re/frida/HostSession"

### ISSUE THREAD

**Issue by Andrewboy159** [AloneMonkey/frida-ios-dump#103]
**Full log:**
`file ../../../frida-core/lib/interfaces/session.vala: line 167: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 're.frida.HostSession12' on object at path /re/frida/HostSession (g-dbus-error-quark, 19)
Segmentation fault: 11
`

I simply tried to run `dump.py -l` and it gave me this error. Seems to me based on _HostSession12_ that it has to do with how I'm using iproxy. Especially given that I'm not sure if I exactly know what I'm doing lol.

**Comment by CPKai** [comment]
Met the same error below when I use command `frida-ps -U`

`file ../../../frida-core/lib/interfaces/session.vala: line 167: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 're.frida.HostSession12' on object at path /re/frida/HostSession (g-dbus-error-quark, 19)`

I uninstall frida tweak on iphone and reinstall it from Cydia. Then the command can work now. Hope this information can help you.

**Comment by Andrewboy159** [comment]
I’ll try it when I can get to my laptop later. I’ve had some problems with installing tweaks and adding sources to Cydia so that could very well be the issue.

**Comment by Andrewboy159** [comment]
Nope, didn't work. Getting the same error. I've tried it on the master and 3.x branches and they both produce the same result. I'm on iOS 13.3 with an iPhone XR on the unc0ver 4.0.0 jailbreak.

**Comment by Andrewboy159** [comment]
Just fixed it. Figured out that I had somehow installed the frida tweak from the wrong repo. It wasn't `https://build.frida.re` and I'm not sure how I did that.
