### ISSUE TITLE
the connection is closed

### ISSUE THREAD

**Issue by gamla11** [AloneMonkey/frida-ios-dump#11]
I try to use this on ios 11 and i open the app that i want to target and use ./dump.py target
Start the target app target
the connection is closed (and app closes) i run it on python27-x64 (also tried x32) with all the requirments installed (except i updated frida from 10.6.58 to 10.6.59.)

**Comment by gamla11** [comment]
and it shows the apps i have installed with -l

only at the end i get those error msgs:
`Traceback (most recent call last):
  File "dump.py", line 297, in <module>
    list_applications(device)
  File "dump.py", line 217, in list_applications
    print line_format % ('-', application.name, application.identifier)
  File "C:\python27-x64\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2011' in position 10: character maps to <undefined>`

**Comment by AloneMonkey** [comment]
I don't have iOS 11 device for the time to find this problem.

**Comment by gamla11** [comment]
allright, it seems to proccess it, only it doesn't export the ipa.

[error.txt](https://github.com/AloneMonkey/frida-ios-dump/files/1808727/error.txt)

**Comment by AloneMonkey** [comment]
Looks like a subprocess problem.

**Comment by gamla11** [comment]
Appearently frida wasn’t updated to 10.7 yet (iOS 11 support) I did use it on my iPhone but not python, will try again later with it updated to

**Comment by gamla11** [comment]
tested it both on 0.7.1 and subprocess errors remain.

**Comment by gamla11** [comment]
Maybe I have to change location of python installation folder (in documents instead of c drive) or have to run as admin.

**Comment by AloneMonkey** [comment]
Or you can try change `chmod` to `/bin/chmod`.

[dump.py line:113](https://github.com/AloneMonkey/frida-ios-dump/blob/master/dump.py#L113)

**Comment by gamla11** [comment]
I did and it haven’t resolved the issue, I assume now the fault might be on my side as I ssh/scp over wifi “192.168.178.178” also I tried to ssh over usb on my MacOs with usbmuxd and tcprelay.py only I keep getting connection refused, but when I ssh root@172.0.0.1 -p 2222 does work but not with dump.py

**Comment by AloneMonkey** [comment]
You can set ip、port and password by yourself.

[dump.py line:33](https://github.com/AloneMonkey/frida-ios-dump/blob/master/dump.py#L33)

**Comment by gamla11** [comment]
Yes I did that

User = 'root'
Password = 'Mypassword'
Host = '172.0.0.1'
Port = 2222 also tried 22

I think I have to connect with scp 1 time normally with 172.0.0.1 before then after it should work, however do u think this could be the reason why it fails?

**Comment by gamla11** [comment]
the ip was the issue, it works.

**Comment by iamleetvin** [comment]
越狱的手机 缺少scp （need scp）
去找一个scp把它放在你手机的/usr/bin目录下面
然后ldid -S scp签名一下
再然后chmod 777 scp给权限
就可以了 it works！！！
