### ISSUE TITLE
Install frida on device

### ISSUE THREAD

**Issue by wikiInit** [AloneMonkey/frida-ios-dump#12]
Install frida on device ， 
Downloading/unpacking frida
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement frida
Cleaning up...
No distributions at all found for frida
Storing debug log for failure in /Users/mac/Library/Logs/pip.log

**Comment by gamla11** [comment]
Open requirements.txt and chance frida==10.6.58 to frida==10.7.1 and run the command “pip install -r requirements” once more
