### ISSUE TITLE
Failed to enumerate applications: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually

### ISSUE THREAD

**Issue by zsbai** [AloneMonkey/frida-ios-dump#133]
报错
Failed to enumerate applications: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually

**Comment by AndreasGassmann** [comment]
@zsbai How were you able to solve this?

**Comment by aress31** [comment]
Why closing this ticket, I have the same issue, what's the fix?

**Comment by wanzhoukaoyu** [comment]
我也遇到这种情况，iPhone6 已越狱，frida版本为14.2.2，执行frida-ps -U 提示Failed to enumerate processes: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually，有什么解决方案？

**Comment by wanzhoukaoyu** [comment]
参考https://www.stevencampbell.info/Test-iOS-Apps-On-Linux/  
下载了和iPhone对应的Xcode-iOS-Developer-Disk-Image，执行
ideviceimagemounter -t Developer DeveloperDiskImage.dmg DeveloperDiskImage.dmg.signature
