### ISSUE TITLE
dump出来的ipa，重新安装到本机运行闪退，Clutch-2.0.4出来的不闪退

### ISSUE THREAD

**Issue by q741451** [AloneMonkey/frida-ios-dump#14]
操作前提：
ipod 6 ios8.4 已经越狱，已经安装AppSync Unified的ipa补丁（依赖Cydia Substrate），已安装frida
MAC 10.13.3，已安装frida-ios-dump脚本和全部依赖

操作步骤：
按照教程，输入./dump.py com.tencent.xin，dump出 微信.ipa 文件
卸载ipod官方微信
将dump出的微信.ipa拷入ipod，使用Filza安装
ipod上执行dump的微信

结果：
点开瞬间闪退

期望：
可以正常运行

其他：
Clutch-2.0.4 dump会失败 但是dump出来的中间文件是解密的，中间文件包含WeChat主程序，用Clutch搞出的解密的WeChat主程序替换闪退的主程序，可以正常打开运行。经过对比二者二进制文件是__LINKEDIT段数据有差异，而且ipod 5 32位CPU也是这个症状，也是__LINKEDIT段数据有差异。附件是ipod 6的两个主程序，一个可运行，一个不可运行。

[WeChat.z01.zip](https://github.com/AloneMonkey/frida-ios-dump/files/1826913/WeChat.z01.zip)
[WeChat.z02.zip](https://github.com/AloneMonkey/frida-ios-dump/files/1826914/WeChat.z02.zip)
[WeChat.z03.zip](https://github.com/AloneMonkey/frida-ios-dump/files/1826915/WeChat.z03.zip)
[WeChat.zip](https://github.com/AloneMonkey/frida-ios-dump/files/1826916/WeChat.zip)

**Comment by wikiInit** [comment]
@q741451   我安装 frida  失败了，sudo pip install frida  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.2-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.2-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.2-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.2-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-BalPp4-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by wikiInit** [comment]
sudo pip install frida -–upgrade –ignore-installed six

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -?

**Comment by wikiInit** [comment]
sudo pip install frida –upgrade –ignore-installed six
The directory '/Users/mac/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/mac/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Invalid requirement: '–upgrade'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.2-py2.7.egg/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/Library/Python/2.7/site-packages/pip-9.0.2-py2.7.egg/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "'\xe2\x80\x93upgra'"

**Comment by q741451** [comment]
@wikiInit 
pip install frida --user -U

**Comment by wikiInit** [comment]
@q741451 
Traceback (most recent call last):
  File "./dump.py", line 19, in <module>
    import paramiko
ImportError: No module named paramiko

**Comment by q741451** [comment]
@wikiInit 
pip install paramiko --user -U

**Comment by wikiInit** [comment]
@q741451   
Traceback (most recent call last):
  File "./dump.py", line 21, in <module>
    from scp import SCPClient
ImportError: No module named scp

**Comment by wikiInit** [comment]
@q741451   我导出来 也闪退   Dylib.dylib: mach-o, but wrong architecture

**Comment by wikiInit** [comment]
dyld: Library not loaded: @executable_path/Frameworks/libtangDylib.dylib

**Comment by q741451** [comment]
@wikiInit 
测了一下，dumpdecrypted.dylib出来的也会闪退，导出的二进制和frida-ios-dump一样

**Comment by wikiInit** [comment]
@q741451 我也试了   都不行，有问题呀，助手他们之前是怎么做的呢

**Comment by wikiInit** [comment]
Clutch 也试了，也不行；

**Comment by q741451** [comment]
@wikiInit 
Clutch可以，执行失败后，到ios的/private/var/tmp目录找Clutch解密的中间文件，里面可以找到已解密的主程序，用里面的主程序替换一下就可以运行了

**Comment by wikiInit** [comment]
@q741451  我是直接用Clutch  打出来的ipa 不行，运行起来报一样的错

**Comment by wikiInit** [comment]
@q741451 也是闪退了，
dyld: Library not loaded: @executable_path/Frameworks/libtangDylib.dylib
 Dylib.dylib: mach-o, but wrong architecture

**Comment by wikiInit** [comment]
@q741451  你这边方便   帮我测一下   导出一个安装包  看会不会也是闪退的

**Comment by q741451** [comment]
问题已解决，Clutch应该是自动签名可执行程序，所以可以运行。
对导出的ipa的可执行主程序，使用以下命令签名即可
codesign -f -s "iPhone Developer" --entitlements signct.xcent WeChat
signct.xcent的内容，大概这个样子
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
            <key>com.apple.springboard.debugapplications</key>
            <true/>
            <key>proc_info-allow</key>
            <true/>
            <key>get-task-allow</key>
            <true/>
            <key>run-unsigned-code</key>
            <true/>
            <key>task_for_pid-allow</key>
            <true/>
</dict>
</plist>
`

**Comment by wikiInit** [comment]
方便留个联系方式

**Comment by wikiInit** [comment]
帮我导个ipa   看看你那边是否OK
