### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by macxstore** [AloneMonkey/frida-ios-dump#15]
./dump.py com.tencent.xin
	Start the target app com.tencent.xin
	Dumping 微信 to /var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T
	start dump /var/containers/Bundle/Application/FC7574FD-C99D-49DE-8130-AF824051424A/WeChat.app/WeChat
	0.00B [00:00, ?B/s]chmod: /var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T/Payload/WeChat.fid: No such file or directory
	Command '('chmod', '655', u'/var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T/Payload/WeChat.fid')' returned non-zero exit status 1
	
	start dump /private/var/containers/Bundle/Application/FC7574FD-C99D-49DE-8130-AF824051424A/WeChat.app/Frameworks/WCDB.framework/WCDB
	0.00B [00:00, ?B/s]chmod: /var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T/Payload/WCDB.fid: No such file or directory
	Command '('chmod', '655', u'/var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T/Payload/WCDB.fid')' returned non-zero exit status 1
	
	start dump /private/var/containers/Bundle/Application/FC7574FD-C99D-49DE-8130-AF824051424A/WeChat.app/Frameworks/MMCommon.framework/MMCommon
	0.00B [00:00, ?B/s]chmod: /var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T/Payload/MMCommon.fid: No such file or directory
	Command '('chmod', '655', u'/var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T/Payload/MMCommon.fid')' returned non-zero exit status 1
	
	start dump /private/var/containers/Bundle/Application/FC7574FD-C99D-49DE-8130-AF824051424A/WeChat.app/Frameworks/MultiMedia.framework/MultiMedia
	0.00B [00:00, ?B/s]chmod: /var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T/Payload/MultiMedia.fid: No such file or directory
	Command '('chmod', '655', u'/var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T/Payload/MultiMedia.fid')' returned non-zero exit status 1
	
	start dump /private/var/containers/Bundle/Application/FC7574FD-C99D-49DE-8130-AF824051424A/WeChat.app/Frameworks/mars.framework/mars
	0.00B [00:00, ?B/s]chmod: /var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T/Payload/mars.fid: No such file or directory
	Command '('chmod', '655', u'/var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T/Payload/mars.fid')' returned non-zero exit status 1
	
	0.00B [00:00, ?B/s]chmod: /var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T/Payload/WeChat.app: No such file or directory
	Command '('chmod', '755', u'/var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T/Payload/WeChat.app')' returned non-zero exit status 1
	
	0.00B [00:00, ?B/s]
	Generating "微信.ipa"
	[Errno 2] No such file or directory: u'/var/folders/7b/c3cyxy3j0t7_tgnt0dh5wc240000gn/T/Payload/WeChat.fid'

环境 MBPr macOS:10.13.3, iPhone 5s iOS:10.1.1

**Comment by macxstore** [comment]
问题解决了，iTerm 设定的字符集问题，重新配置了zsh就好了

**Comment by lslboy** [comment]
具体怎么重新配置的，大佬，急求

**Comment by littlegirlpppp** [comment]
同问

**Comment by tqhnet** [comment]
同问

**Comment by tqhnet** [comment]
解决了兄弟们，手机安装openssh
