### ISSUE TITLE
Stuck on "Start the target app Twitter"

### ISSUE THREAD

**Issue by CobreDev** [AloneMonkey/frida-ios-dump#155]
I'm trying to decrypt Twitter for iOS, and whenever I run frida it gets stuck on "Start the target app Twitter."

My specs:
Frida 14.2.18 on macOS Big Sur 11.3.1
Frida 14.2.18 on iPhone 7 iOS 14.5 jailbroken with odysseyra1n

**Comment by Un1q32** [comment]
you have to launch the twitter app from your iphone while the script is running

**Comment by CobreDev** [comment]
I think I figured out my issue, it was a it more than that.

**Comment by Fabi** [comment]
> I think I figured out my issue, it was a it more than that.
> […](#)
> On May 30, 2021, at 22:16, oofmaster69420 ***@***.***> wrote: ﻿ you have to launch the twitter app from your iphone while the script is running — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Any hints no that? I'm stuck on the same issue

**Comment by Living-Lemming** [comment]
can you say how you fixed it?
