### ISSUE TITLE
Error when trying to dump ipa file

### ISSUE THREAD

**Issue by TwistedAlex** [AloneMonkey/frida-ios-dump#156]
OS: IOS 12.2
unc0ver jailbreak
Device: ipad air
error message when $ python dump.py com.meteor.Zao:
    Generating "Zao.ipa"
    [Errno 2] No such file or directory: 'zip'

**Comment by staukini** [comment]
I'm having the same error.

I'm using an iPhone 6s with an installed OpenSSH server. 
dump.py -l does work but I'm having problems exporting the dump.

does anyone have solved that issue?

**Comment by staukini** [comment]
@TwistedAlex you closed that Issue already. Have you solved it probably yourself?

best wishes

**Comment by TwistedAlex** [comment]
My issue is that my local os doesn't have zip installed. Hope this helps.
