### ISSUE TITLE
unexpected error while resuming process: (os/kern) failure

### ISSUE THREAD

**Issue by wangxiaobupt** [AloneMonkey/frida-ios-dump#16]
一运行就报kern错误

frida-ios-dump-master ./dump.py 微信
Start the target app 微信
unexpected error while resuming process: (os/kern) failure

accepted connection, fd = 6
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 80 (serial: 83aaaaef391884c5ce7034df8131447054ad2841), port 22
run_ctos_loop: fd = 6
run_stoc_loop: fd = 6
recv failed: Resource temporarily unavailable

**Comment by wangxiaobupt** [comment]
解决了

**Comment by Peterae** [comment]
> 解决了

请问怎么解决的，我也遇到这个问题，但没你这么多报错信息，就这一句
unexpected error while probing dyld of target process

**Comment by DennyChen0** [comment]
> 解决了

分享下怎么解决的呗
