### ISSUE TITLE
Error while dumping app connection closed 

### ISSUE THREAD

**Issue by 0xsalih** [AloneMonkey/frida-ios-dump#163]
Hi Team,

I'm able to list all the apps source (python3 dump.py -l). However I'm facing issues while loading the app, for example I did (python3 dump.py com.google.ios.youtube). It just launches the app and disappear after with below error. Any help is highly appreciated.

frida-ios-dump % python3 dump.py com.google.ios.youtube
Start the target app com.google.ios.youtube
connection closed

Dec 10 10:21:40 mediaanalysisd-service(VideoProcessing)[1737] <Notice>: VCPSceneTaxonomy - cannot find scene id for scene name <private>
Dec 10 10:21:40 sshd(libsystem_info.dylib)[1740] <Error>: send failed: Invalid argument
Dec 10 10:21:40 sshd(libsystem_info.dylib)[1740] <Error>: send failed: Invalid argument
Dec 10 10:21:40 sshd(libsystem_info.dylib)[1740] <Error>: send failed: Invalid argument
Dec 10 10:21:41 trustd[489] <Notice>: cert[0]: MissingIntermediate =(leaf)[force]> 0

Dec 10 10:21:41 lockdownd[444] <Notice>: spawn_xpc_service: <private>
Dec 10 10:21:41 debugserver(substitute-loader.dylib)[1742] <Error>: ExtensionLoader <private>: Safemode parent directory <private> is blocked by sandbox.
Dec 10 10:21:42 debugserver(!ABypass2.dylib)[1742] <Error>: [Tweak.xm:221] Hello! Jailbreak Detection! A-Bypass is Loading...
Dec 10 10:21:42 debugserver(!ABypass2.dylib)[1742] <Error>: [Tweak.xm:222] A-Bypass by Baw Appie <pp121324@gmail.com>
Dec 10 10:21:42 debugserver(substitute-loader.dylib)[1742] <Error>: ExtensionLoader <private>: Injection of <private> failed: '<private>'
Dec 10 10:21:42 debugserver[1742] <Notice>: debugserver will use ASL for internal logging.

Dec 10 10:21:43 trustd[489] <Notice>: cert[0]: IntermediateMarkerOid =(path)[force]> 0
Dec 10 10:21:43 debugserver(DVTInstrumentsFoundation)[1742] <Error>: Connection received zero bytes, EOF.
Dec 10 10:21:43 debugserver(DVTInstrumentsFoundation)[1742] <Error>: Socket read error (89): Operation canceled.
Dec 10 10:21:43 DTServiceHub(DVTInstrumentsFoundation)[1616] <Error>: Connection received zero bytes, EOF.
Dec 10 10:21:43 debugserver[1742] <Notice>: debugserver's event read thread is exiting, killing the inferior process.
Dec 10 10:21:43 DTServiceHub(DVTInstrumentsFoundation)[1616] <Error>: Socket read error (89): Operation canceled.
Dec 10 10:21:43 debugserver[1742] <Notice>: debugserver secure socket proxy finish-block shut down.

iproxy 222 22
iPhone XR A12 - frida server A12+
idevicepair pair
ssh root@ip - success

**Comment by 0xsalih** [comment]
iproxy 2222 22
Creating listening port 2222 for device port 22
waiting for connection
New connection for 2222->22, fd = 5
waiting for connection
Requesting connecion to USB device handle 150 (serial: 00008020-00095D802106002E), port 22
New connection for 2222->22, fd = 5
waiting for connection
Requesting connecion to USB device handle 150 (serial: 00008020-00095D802106002E), port 22

**Comment by novitae** [comment]
I'm on iPhone XR too, I installed Frida A12+ on my device, and this was what was causing this `connection close` exit. I downgraded to the simple Frida (should be the first package in cydia) and it works now.

**Comment by 0xsalih** [comment]
yeah, i already did the same :)
