### ISSUE TITLE
jailbroke 15.3.1 by palera1n, not working

### ISSUE THREAD

**Issue by levinl** [AloneMonkey/frida-ios-dump#172]
$ frida-ps -U | grep 下厨房
1601  下厨房                                                     

$ python3 dump.py 下厨房
Start the target app 下厨房
unable to attach to the specified process

the way worked in iOS 12

**Comment by levinl** [comment]
砸成功了！

**Comment by jdjingdian** [comment]
> 砸成功了！

请教一下你是如何操作成功的呢

**Comment by zljkevin** [comment]
请问一下 palera1n有根越狱怎么成功的，我ssh一直拿不到root权限

**Comment by hunterxxx** [comment]
> 请问一下 palera1n有根越狱怎么成功的，我ssh一直拿不到root权限

sudo su
