### ISSUE TITLE
UNIX authentication refused

### ISSUE THREAD

**Issue by SuFu123** [AloneMonkey/frida-ios-dump#178]
我在越狱的设备（ios15.7）上使用ssh连接时提示UNIX authentication refused，但是用户名与密码都是正确的，请问这种该怎么解决

**Comment by L0veHeather** [comment]
建议在越狱的手机上搞个mterminal，修改一下root的密码。再尝试用新的密码ssh连接

**Comment by fakeGourmet** [comment]
先 `ssh -p 2222 mobile@127.0.0.1`，在用户态执行 `sudo passwd root` 把密码更新下，然后重试下 `ssh -p 2222 root@127.0.0.1` 就行了
