### ISSUE TITLE
脱壳无法成功

### ISSUE THREAD

**Issue by 1in3r** [AloneMonkey/frida-ios-dump#185]
dump.py 能够跑到最后,并且生成ipa 但是没有脱壳成功
脱壳过程中 一直提示类似 scp 没有权限无法拷贝的错误
scp.SCPException: scp: /var/mobile/Containers/Data/Application/D94339F9-2F5B-430F-AB56-E9475C704F28/Documents/XXXXX.fid: Operation not permitted
这样的错误?
我SSH 登录到iphone上 发现/var/mobile/Containers/Data/ 目录下的内容就已经无法访问了. ls都不行
但是 通过iFunbox 到对应的目录下却能够访问!
不知道有没有人碰到这样的问题?

**Comment by HUAQW0** [comment]
解决了吗，我也生成了ipa，没脱成功
