### ISSUE TITLE
[Errno None] Unable to connect to port 2222 on 127.0.0.1

### ISSUE THREAD

**Issue by yikibug** [AloneMonkey/frida-ios-dump#19]
I have opend the application before dumping,  the console show error "Unable to connect...",
but input ./dump.py command, it can show all installed apps.

**Comment by AloneMonkey** [comment]
Did you run `iproxy 2222 22`?
Can you login in with `ssh root@localhost -p 2222`?

**Comment by yikibug** [comment]
Thanks, I forget to open port map(2222->22).

**Comment by jack4n6** [comment]
i also interfere with this kind of error, the apps list can be show but after i want to patch it suddenly error "Unable to connect.." appear. Any thought?
