### ISSUE TITLE
dump一次后，打开其他应用直接闪退

### ISSUE THREAD

**Issue by YGAS** [AloneMonkey/frida-ios-dump#2]
## 设备信息
iPod Touch 5,
iOS 9.3.5
----------
## 详细描述
1. 输入一次./dump.py xx后，打开其他应用直接闪退，只有之前dump的应用可以正常打开。
2. 如果没有事先把需要dump的应用加载到前台，应用会在执行到`session = device.attach(target);`的时候自动闪退

**Comment by AloneMonkey** [comment]
Can you provide a crash log?

**Comment by YGAS** [comment]
sorry, there were no crash log on the device.
![4b2a6a47-873c-4c54-8e7a-6c71aedcf537](https://user-images.githubusercontent.com/1214708/35729242-052d0be6-0849-11e8-8f48-614eac990cf9.png)

**Comment by AloneMonkey** [comment]
ok, I'll test later on 32bit machine.

**Comment by AloneMonkey** [comment]
i just test on 32-bit device and run well

**Comment by YGAS** [comment]
Maybe it's the jailbreak's problem. My jailbreak base on [Phoinex](https://phoenixpwn.com/).

**Comment by AloneMonkey** [comment]
it's not iPod Touch 5?

**Comment by YGAS** [comment]
Yes,it's touch 5.iOS 9.3.5.

**Comment by YGAS** [comment]
i found the only way to jailbreak 9.3.5. it's the Phoenix.

**Comment by AloneMonkey** [comment]
I misunderstood，you can debug the dump script

**Comment by YGAS** [comment]
Yes, I will.

**Comment by YGAS** [comment]
More info. Use `./dump.py LINE` result in dump failed and crash.
`./dump.py -b jp.naver.line` dump success.
Can you provide some advice.
 I don't know  how to debug further.

**Comment by AloneMonkey** [comment]
Didn't you insert `print` or `console.log` to script file?

you can check function `getbundleid` in `app.js`

**Comment by YGAS** [comment]
`./dump.py -b jp.naver.line` was faild actually.
`get_pid_by_bundleid(bundleid)` return 0.
![image](https://user-images.githubusercontent.com/1214708/35901153-47efaacc-0c10-11e8-9b9e-9d1423434e5c.png)

**Comment by YGAS** [comment]
The trouble seems in the `openApplication` function. Tha app open then crash in my iPod. So the pid was wrong.
## the code
```
function openApplication(appid){
	console.log(openApplication);
	console.log(appid);
	const workspace = LSApplicationWorkspace.defaultWorkspace();
	return workspace.openApplicationWithBundleID_(appid);
}
```
## the log
```
open target app......
<frida.core.Session object at 0x1061f8e50>
handleMessage
success
jp.naver.line
function openApplication() { [ecmascript code] }
jp.naver.line
Waiting for the application to open......
```

**Comment by AloneMonkey** [comment]
maybe your device don't have function `workspace.openApplicationWithBundleID`

**Comment by YGAS** [comment]
I have solve the problem by change the "springboard" to "邮件".
It's the session's fault. Maybe my device can't attach "springboard"?
```
def open_target_app(isbundleid, value):
	device = get_usb_iphone();
	name = u'邮件';
	print "open target app......"
	session = device.attach(name);
	print session
	script = load_js_file(session, APP_JS);
	if not isbundleid:
		script.post({'name': value})
	else:
		script.post({'bundleid': value})
	opened.wait();
	session.detach();
	create_dir(os.getcwd()+"/"+OUTPUT)
	print 'Waiting for the application to open......'
	time.sleep(5);
```

**Comment by AloneMonkey** [comment]
nop, Above you have output the value of the session，so It has been attached to SpringBoard.

**Comment by YGAS** [comment]
Yes, the attach was successed. But it crashed when device attach to SpringBoard.

**Comment by AloneMonkey** [comment]
Comment the code following `device.attach(name)`，Will crashed?

**Comment by YGAS** [comment]
NO.This code will crash.
```
def open_target_app(isbundleid, value):
	device = get_usb_iphone();
	# name = u'邮件';
	name = u'SpringBoard';
	print "open target app......"
	session = device.attach(name);
	print session
	script = load_js_file(session, APP_JS);
	if not isbundleid:
		script.post({'name': value})
	else:
		script.post({'bundleid': value})
	# opened.wait();
	# session.detach();
	# create_dir(os.getcwd()+"/"+OUTPUT)
	# print 'Waiting for the application to open......'
	# time.sleep(5);
```

**Comment by AloneMonkey** [comment]
ok, you can try pull request at first, I will merge code at night. Then you can try again

**Comment by YGAS** [comment]
I think change the 'SpringBoard' to '邮件' is not a common solution.
And '邮件' may change base on the area of system.
So the code can not be merged, i think.

**Comment by AloneMonkey** [comment]
I am talking about merging pull request code

**Comment by YGAS** [comment]
ok. I made the request.

**Comment by AloneMonkey** [comment]
You mean you can try this
https://github.com/AloneMonkey/frida-ios-dump/pull/4

**Comment by YGAS** [comment]
Oh,I misunderstood. I will try it.

**Comment by YGAS** [comment]
e, It has some error about SSH. It may need some extra operation. I will try it latter.
```
No handlers could be found for logger "paramiko.transport"
*** Caught exception: <class 'paramiko.ssh_exception.SSHException'>: Error reading SSH protocol banner[Errno 54] Connection reset by peer
Traceback (most recent call last):
  File "./dump.py", line 295, in <module>
    ssh.connect(Host, port=Port, username=User, password=Password)
  File "/Library/Python/2.7/site-packages/paramiko/client.py", line 392, in connect
    t.start_client(timeout=timeout)
  File "/Library/Python/2.7/site-packages/paramiko/transport.py", line 545, in start_client
    raise e
SSHException: Error reading SSH protocol banner[Errno 54] Connection reset by peer
```

**Comment by AloneMonkey** [comment]
can you login by `ssh root@localhost -p 2222` ?

**Comment by AloneMonkey** [comment]
You can config the following information in `dump.py`:

```
User = 'root'
Password = 'alpine'
Host = 'localhost'
Port = 2222
```

**Comment by AloneMonkey** [comment]
@YGAS updated, try again.

**Comment by YGAS** [comment]
`./dump.py 2Do` failed. `./dump.py -l` successd.
`[Errno None] Unable to connect to port 2222 on 10.1.133.11`

**Comment by YGAS** [comment]
And the old code work fine.

**Comment by AloneMonkey** [comment]
If you connect by ip, set port to default 22

**Comment by AloneMonkey** [comment]
Open the application and then run the script, try.

**Comment by YGAS** [comment]
en, open and dump will success.
