### ISSUE TITLE
在使用工具的时候，出现一个问题！

### ISSUE THREAD

**Issue by xavierXing** [AloneMonkey/frida-ios-dump#20]

**Comment by xavierXing** [comment]
No handlers could be found for logger "paramiko.transport"
*** Caught exception: <class 'paramiko.ssh_exception.SSHException'>: Error reading SSH protocol banner[Errno 54] Connection reset by peer
Traceback (most recent call last):
  File "./dump.py", line 306, in <module>
    ssh.connect(Host, port=Port, username=User, password=Password)
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 392, in connect
    t.start_client(timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/paramiko/transport.py", line 545, in start_client
    raise e
SSHException: Error reading SSH protocol banner[Errno 54] Connection reset by peer

**Comment by xavierXing** [comment]
这是输出的日志，显示没有 "paramiko.transport" 这个东西， 由于我对python不是很熟悉，不敢妄加修改代码；请庆哥看一下这个问题是什么原因引起的，ssh链接我手动链接是可以的。

**Comment by AloneMonkey** [comment]
https://github.com/AloneMonkey/frida-ios-dump/blob/master/dump.py#L32

**Comment by bjzz** [comment]
kill -9 pid(iproxy)  and try again
