### ISSUE TITLE
工具出错，导不出ipa

### ISSUE THREAD

**Issue by sonwa** [AloneMonkey/frida-ios-dump#21]
./dump.py com.laiwang.DingTalk
Start the target app com.laiwang.DingTalk
Dumping 钉钉 to /var/folders/66/vj8tq0cx16b5_4cvq8ysg5240000gp/T
start dump /var/containers/Bundle/Application/4E62A975-C915-4DD9-81C4-BD7D1ED718C1/DingTalk.app/DingTalk
0.00B [00:00, ?B/s]chmod: /var/folders/66/vj8tq0cx16b5_4cvq8ysg5240000gp/T/Payload/DingTalk.fid: No such file or directory
Command '('chmod', '655', u'/var/folders/66/vj8tq0cx16b5_4cvq8ysg5240000gp/T/Payload/DingTalk.fid')' returned non-zero exit status 1

start dump /private/var/containers/Bundle/Application/4E62A975-C915-4DD9-81C4-BD7D1ED718C1/DingTalk.app/Frameworks/DTSharedFramework.framework/DTSharedFramework
0.00B [00:00, ?B/s]chmod: /var/folders/66/vj8tq0cx16b5_4cvq8ysg5240000gp/T/Payload/DTSharedFramework.fid: No such file or directory
Command '('chmod', '655', u'/var/folders/66/vj8tq0cx16b5_4cvq8ysg5240000gp/T/Payload/DTSharedFramework.fid')' returned non-zero exit status 1

0.00B [00:00, ?B/s]chmod: /var/folders/66/vj8tq0cx16b5_4cvq8ysg5240000gp/T/Payload/DingTalk.app: No such file or directory
Command '('chmod', '755', u'/var/folders/66/vj8tq0cx16b5_4cvq8ysg5240000gp/T/Payload/DingTalk.app')' returned non-zero exit status 1

0.00B [00:00, ?B/s]Generating "钉钉.ipa"
[Errno 2] No such file or directory: u'/var/folders/66/vj8tq0cx16b5_4cvq8ysg5240000gp/T/Payload/DingTalk.fid'

**Comment by sonwa** [comment]
请问这个是啥问题？

**Comment by keepyounger** [comment]
我也遇到了

**Comment by AloneMonkey** [comment]
Must confirm that ssh and scp are available!
