### ISSUE TITLE
No module named paramiko ，貌似是python环境问题

### ISSUE THREAD

**Issue by mgfjxxiexiaolong** [AloneMonkey/frida-ios-dump#22]
有点莫名其妙，之前是好的，看看有没有遇到相同情况的
<img width="592" alt="qq20180515-142317 2x" src="https://user-images.githubusercontent.com/13596540/40040244-0836d7d2-57df-11e8-98a6-ad4330dd89c7.png">

**Comment by coleflowers** [comment]
sudo pip install paramiko

**Comment by AloneMonkey** [comment]
Recommand using Anaconda!

**Comment by mgfjxxiexiaolong** [comment]
> Recommand using Anaconda!

用 Anaconda装了paramiko 还是提示一样问题，是我操作不对吗？

**Comment by XLsn0w** [comment]
Traceback (most recent call last):
  File "./dump.py", line 19, in <module>
    import paramiko
