### ISSUE TITLE
error info: connection is closed and ios device reboot

### ISSUE THREAD

**Issue by bjzz** [AloneMonkey/frida-ios-dump#26]
$iproxy 2222 22
waiting for connection
accepted connection, fd = 4
waiting for connection
Number of available devices == 2
Requesting connecion to device handle == 5 (serial: ac3be5085b47fae1e0e99db785b6bb5af8faeb56), port 22
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable

$ ./dump.py yueche
Start the target app yueche
the connection is closed

**Comment by AloneMonkey** [comment]
https://github.com/AloneMonkey/frida-ios-dump#issues
