### ISSUE TITLE
ssh_exchange_identification: read: Connection reset by peer

### ISSUE THREAD

**Issue by YGAS** [AloneMonkey/frida-ios-dump#3]
## 设备
iPod Touch 5,
iOS 9.3.5
## 描述
dump使用库比较多的应用，例如即刻。
1. 每一个库都需要输入输入一次ssh密码。这一步是必须的吗，还是有什么优化方案
2. 即刻的ipa到最后都没有成功dump出来。因为到最后几个库的时候，出现了`ssh_exchange_identification: read: Connection reset by peer`，导致缺少对应的库
## 最终错误
`[Errno 2] No such file or directory: u'/Users/xxx/Documents/frida-ios-dump/Payload/libswiftPhotos.dylib'`

**Comment by AloneMonkey** [comment]
1. you can login without password by:

```
ssh-keygen -t rsa -P ''
ssh-copy-id -i /Users/username/.ssh/id_rsa root@ip
```

2. Connection reset by peer is because connection is unstable。

**Comment by AloneMonkey** [comment]
I find a bug on dumpping jike, please update to latest code to dump.

**Comment by YGAS** [comment]
ok, thanks.
