### ISSUE TITLE
Error code when dump file

### ISSUE THREAD

**Issue by hanv10** [AloneMonkey/frida-ios-dump#30]
Hi, I have this error when run frida-ios-dump. Please advise

MacBook-Air:frida-ios-dump Admin$ ./dump.py -o iOSAPP.ipa com.will.go
*** Caught exception: <type 'exceptions.ImportError'>: dlopen(/Library/Python/2.7/site-packages/cryptography-2.2.2-py2.7-macosx-10.13-intel.egg/cryptography/hazmat/bindings/_openssl.so, 2): Symbol not found: _d2i_DHxparams
  Referenced from: /Library/Python/2.7/site-packages/cryptography-2.2.2-py2.7-macosx-10.13-intel.egg/cryptography/hazmat/bindings/_openssl.so
  Expected in: flat namespace
 in /Library/Python/2.7/site-packages/cryptography-2.2.2-py2.7-macosx-10.13-intel.egg/cryptography/hazmat/bindings/_openssl.so
Traceback (most recent call last):
  File "./dump.py", line 306, in <module>
    ssh.connect(Host, port=Port, username=User, password=Password)
  File "build/bdist.macosx-10.13-intel/egg/paramiko/client.py", line 392, in connect
    t.start_client(timeout=timeout)
  File "build/bdist.macosx-10.13-intel/egg/paramiko/transport.py", line 545, in start_client
    raise e
ImportError: dlopen(/Library/Python/2.7/site-packages/cryptography-2.2.2-py2.7-macosx-10.13-intel.egg/cryptography/hazmat/bindings/_openssl.so, 2): Symbol not found: _d2i_DHxparams
  Referenced from: /Library/Python/2.7/site-packages/cryptography-2.2.2-py2.7-macosx-10.13-intel.egg/cryptography/hazmat/bindings/_openssl.so
  Expected in: flat namespace
 in /Library/Python/2.7/site-packages/cryptography-2.2.2-py2.7-macosx-10.13-intel.egg/cryptography/hazmat/bindings/_openssl.so
MacBook-Air:frida-ios-dump Admin$ 

Thank you!

**Comment by AloneMonkey** [comment]
Please read help message:

```
usage: dump.py [-h] [-l] [-o OUTPUT_IPA] [target]

frida-ios-dump (by AloneMonkey v2.0)

positional arguments:
  target                Bundle identifier or display name of the target app

optional arguments:
  -h, --help            show this help message and exit
  -l, --list            List the installed apps
  -o OUTPUT_IPA, --output OUTPUT_IPA
                        Specify name of the decrypted IPA
```
