### ISSUE TITLE
Can't run dump.py. Waiting for USB device...

### ISSUE THREAD

**Issue by linhmui** [AloneMonkey/frida-ios-dump#32]
Hi
When i try using dump.py in terminal, it show that:

File "/Users/LinhMui/Downloads/frida-ios-dump-master/dump.py", line 58
    print 'Waiting for USB device...'
                                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Waiting for USB device...')?

![image](https://user-images.githubusercontent.com/18011987/42558124-8039ec0c-851a-11e8-8d71-404a9b981da7.png)

Although i connect success with iproxy 2222 22 and using ssh root@localhost -p 2222

![image](https://user-images.githubusercontent.com/18011987/42558201-bcd00ad4-851a-11e8-8c5a-7e08a1de44e6.png)

Please help
Thanks

**Comment by AloneMonkey** [comment]
You can switch to 3.x branch.

**Comment by linhmui** [comment]
Thanks for quick reply. But i used Python 3.7 and using **"Python3.7 ./dump.py"** but it still show "Waiting for USB device". How to fix them? In my MAC cant install Frida with 2.7 pre install on Mac 10.12

Thanks

**Comment by MuchiMuchiPink** [comment]
Same problem

**Comment by AloneMonkey** [comment]
@linhmui  update frida on mac and iphone device. Then pull lastest frida-ios-dump code.

**Comment by linhmui** [comment]
@AloneMonkey Thanks. Lets me try

**Comment by AloneMonkey** [comment]
Do you update frida-ios-dump ?

**Comment by AloneMonkey** [comment]
yes, 3.x branch use python 3

**Comment by luoyanbei** [comment]
I got the same issue .My frida version is 12.0.6.
You can try:
1. find "/opt/MonkeyDev/bin/dump.py" file and change "if dev.type == 'tether'" to "if dev.type == 'usb'"
2. find dump.py in frida-ios-dump-master and change "if dev.type == 'tether'" to "if dev.type == 'usb'"
3. input "./dump.py appname" in terminal, it output "Waiting for USB device..."
4. connect your iphone to your mac by usb, you can see message "Start the target app appname" and it satrt to dump.

**Comment by AloneMonkey** [comment]
Lastest code had fixed this problem.

**Comment by linhmui** [comment]
@alonemonkey seem to be issue is python2 code not compatible with python 3. So please update code for python3. I used other folk frida dump was normal

Thanks

**Comment by BrianHenryIE** [comment]
Changing USB cable worked for me.

**Comment by AT5HK** [comment]
changing to 3.x branch didn't work for me.

I had to restart my computer and respring my iphone for it to work lol. respringing my iphone probably would of been sufficient.
