### ISSUE TITLE
最新版frida兼容

### ISSUE THREAD

**Issue by tobefuturer** [AloneMonkey/frida-ios-dump#33]
devices = [dev for dev in device_manager.enumerate_devices() if dev.type == 'tether']

dev.type 貌似变成usb了

[Device(id="cb626dc71d1a8e23893830c33cd4d2e861d5ae40", name="iPhone", type='usb')]

**Comment by Nomeqc** [comment]
+1

**Comment by AloneMonkey** [comment]
fixed
