### ISSUE TITLE
环境都配好了，一直显示：Waiting for USB device...

### ISSUE THREAD

**Issue by zljkevin** [AloneMonkey/frida-ios-dump#37]
一直显示；
dump.py com.laiwang.DingTalk
Waiting for USB device...

iOS10.0.2，没有安装scp,（一直没找到，求一个scp）。

端口也设置好了：
iproxy 2235 22
waiting for connection

ssh也能登上去：
CCiPhone:~ root#

**Comment by AloneMonkey** [comment]
https://github.com/AloneMonkey/frida-ios-dump/issues/32#issuecomment-406457248

**Comment by AloneMonkey** [comment]
> iOS10.0.2，没有安装scp,（一直没找到，求一个scp）。

书上有。
