### ISSUE TITLE
ImportError: No module named frida ,Please Help

### ISSUE THREAD

**Issue by gbm777** [AloneMonkey/frida-ios-dump#38]
`guobaomingdeMac:frida-ios-dump guobaoming$ dump.py
Traceback (most recent call last):
  File "/opt/dump/frida-ios-dump/dump.py", line 9, in <module>
    import frida
ImportError: No module named frida`

**Comment by gbm777** [comment]
@AloneMonkey

**Comment by AloneMonkey** [comment]
pip install

**Comment by linxuebin1990** [comment]
> But still the same error.

I think your python is mac self, try this cmd "python -m pip install frida-tools"

**Comment by russell-shizhen** [comment]
Run command `$ pip --version` and `$ pip3 --version` to check which *pip* is from at **Python 3x**.  E.g. you should see version information like below:
```bash
pip 19.0.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```
Then run the right **pip** command to install `frida-tools`, e.g.  `pip3` 
```bash
$ pip3 install frida-tools
```

Then run the `example.py` script with below command
```bash
$ python3 example.py
```

**Comment by poldenais** [comment]
Hi All, 
Im getting the same issue.

**Comment by ybaktir** [comment]
https://stackoverflow.com/a/58617606/11079758

**Comment by richpowell** [comment]
if you have python3 try this to execute dump.py
`python3 ./dump.py`

**Comment by 393698063** [comment]
python3 dump.py -l
Traceback (most recent call last):
  File "dump.py", line 11, in <module>
    import frida
ModuleNotFoundError: No module named 'frida'

**Comment by nanier** [comment]
> if you have python3 try this to execute dump.py `python3 ./dump.py`

This help me to solve the problem.

**Comment by ZuhanLin** [comment]
> 
python3 dump.py 
Traceback (most recent call last):
  File "dump.py", line 11, in <module>
    import frida
ModuleNotFoundError: No module named 'frida'


me too

**Comment by flamecopper** [comment]
python3 -m pip install frida
This was what solves my problem
