### ISSUE TITLE
中文app显示乱码，造成dump失败

### ISSUE THREAD

**Issue by gbm777** [AloneMonkey/frida-ios-dump#42]
adeMac:~ a$ frida-ps -U
 PID  Name
----  -----------------------------------------------
1227  InCallService
2645  SafariViewService
2683  ç¨æ·é´å®
2824  ç¥åå¥è¿¹
2793  é±å
2817  AKLocationSignInAlert
2790  CloudKeychainProxy
 981  CommCenter

**Comment by gbm777** [comment]
adeMac:frida-ios-dump a$ sudo ./dump.py 2683
Start the target app 2683
unable to launch iOS app: The operation couldn’t be completed. Application "" is unknown to FrontBoard.
adeMac:frida-ios-dump a$

**Comment by gbm777** [comment]
@AloneMonkey

**Comment by AloneMonkey** [comment]
Please read [README](https://github.com/AloneMonkey/frida-ios-dump/blob/master/README.md) first!

```
Run ./dump.py Display name or Bundle identifier
```

**Comment by gbm777** [comment]
sudo ./dump.py Bundle identifier 能解决中文问题和permission denied的问题。谢谢！
