### ISSUE TITLE
unable to launch iOS app: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 4.)

### ISSUE THREAD

**Issue by tepmnthar** [AloneMonkey/frida-ios-dump#47]
Most apps can be dumped, while there's one app always shows `unable to launch iOS app: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 4.)`.
What does this mean? And how can I fix it? Needs for help, please.

Found another output `unexpected error while probing dyld of target process` also stops the dumping procedure.

**Comment by AloneMonkey** [comment]
You can launch the target app before dumping.

**Comment by tepmnthar** [comment]
OK, maybe there are some weird Unicode char in the app name. Turn to use its bundle id and it works.
Thank you. What about dyld error? Is there any way to prevent someone from dumping my app?

**Comment by AloneMonkey** [comment]
This is a problem with the frida spawn function.   If this is the case, it is best to open the app and then dump.

**Comment by tepmnthar** [comment]
Got it! 👍

**Comment by ytx0574** [comment]
unable to launch iOS app: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)

此问题同上, 先打开

**Comment by qweqwqsqwwew** [comment]
我也是，一直这样

**Comment by stanle1** [comment]
got it

**Comment by Dodong1212** [comment]
Thanks
