### ISSUE TITLE
ios12 怎么修改？

### ISSUE THREAD

**Issue by insomnia417** [AloneMonkey/frida-ios-dump#53]
dump.py出来错误spawn already in progress for the specified identifier
expecting to read a single byte for receiving credentials but read zero bytes
打开app后马上闪退

**Comment by xiangcong** [comment]
@insomnia417 请问后面怎么解决的？

**Comment by insomnia417** [comment]
解决不了 等修复吧  这次ios12的越狱跟之前elctra不太一样 包括clutch也是没法工作 ，

**Comment by mgfjxxiexiaolong** [comment]
我这边是直接导致6s设备重启了 ， 5s设备无法启动对象app并直接结束，坐等更新。包括clutch、dumpdecrypted都无法正常工作
