### ISSUE TITLE
start dump /var/containers/Bundle/Application/    0.00B [00:00, ?B/s]

### ISSUE THREAD

**Issue by zyxiaofeng** [AloneMonkey/frida-ios-dump#58]
start dump /var/containers/Bundle/Application/84D4939D-D087-4105-A4DD-763A657D2088/XWX.app/XWX
0.00B [00:00, ?B/s]

请问  这是什么原因呢？

**Comment by Marcello168** [comment]
@ @zyxiaofeng 我也遇到了，请问下这是什么原因呢？ 找到解决的方案了吗

**Comment by WCMYCML** [comment]
> start dump /var/containers/Bundle/Application/84D4939D-D087-4105-A4DD-763A657D2088/XWX.app/XWX
> 0.00B [00:00, ?B/s]
> 
> 请问 这是什么原因呢？

我也遇到了，请问是怎么解决呢？我目前还没找到解决方案
