### ISSUE TITLE
frida 12.5.0不执行dump.js

### ISSUE THREAD

**Issue by DogSuisui** [AloneMonkey/frida-ios-dump#65]
➜  frida-ios-dump git:(master) python dump.py 叉叉助手
/usr/local/lib/python2.7/site-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())
/usr/local/lib/python2.7/site-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.curve, Q_S_bytes
/usr/local/lib/python2.7/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  hm.add_string(self.Q_C.public_numbers().encode_point())
Start the target app 叉叉助手
Dumping 叉叉助手 to /var/folders/4y/mrgy0_hx2nv0bxtl7yzpsnxc0000gn/T
0.00B [00:00, ?B/s]

卡在这里了，看了下dump.js没有被执行，frida 12.5.0 ,frida-tools 1.3.2

**Comment by Pilfer** [comment]
Having the same issue here. Frida server 12.5.0, local frida version: 12.5.0. 

I get the same deprecation warnings @DogSuisui has, and the same `0.00B [00:00, ?B/s]` string output to console. I'm running Chimera if that matters.

**Comment by Pilfer** [comment]
Just following up, I was able to confirm that downgrading frida-server to 11.4.8 works fine, leading me to believe there is likely an incompatibility issue somewhere.

Instructions for those who are stuck: Download the 11.4.8 frida-server for iOS from the releases page. Place the file in /usr/sbin/ - you'll probably want to rename the old frida-server to `frida-12.5.0` or something. Run `ps aux | grep "frida"` to get the PID of the existing frida-server process, and `kill -9 <the pid here>`. chmod your new frida-server to 755 and run it. It should just work after that.

**Comment by AloneMonkey** [comment]
fixed
