### ISSUE TITLE
start dump /var/containers/Bundle/Application/ 0.00B [00:00, ?B/s] 

### ISSUE THREAD

**Issue by Marcello168** [AloneMonkey/frida-ios-dump#66]
这是怎么回事呢？

dump.py com.tencent.mttlite
Start the target app com.tencent.mttlite
Dumping QQ浏览器 to /var/folders/dr/gm31l1fd2hx5_289_xlv6kmr0000gn/T
0.00B [00:00, ?B/s]

**Comment by AloneMonkey** [comment]
fixed
