### ISSUE TITLE
dump时速度一直为0

### ISSUE THREAD

**Issue by Goodman333** [AloneMonkey/frida-ios-dump#75]
![image](https://user-images.githubusercontent.com/9305248/60697058-fa5ee580-9f1a-11e9-85aa-a1f985deca9f.png)
dump时，一直卡在这里，请问有什么解决办法吗

**Comment by paradiseduo** [comment]
我也是这样，iOS10.0.2

**Comment by Goodman333** [comment]
> 我也是这样，iOS10.0.2

我是iOS10.2.1，请问你解决了吗

**Comment by Goodman333** [comment]
iOS10之后的设备重新安装了OpenSSH就可以了
