### ISSUE TITLE
  File "./dump.py", line 19, in <module>     import paramiko ImportError: No module named paramiko

### ISSUE THREAD

**Issue by XLsn0w** [AloneMonkey/frida-ios-dump#77]
./dump.py -l
报错 
Traceback (most recent call last):
  File "./dump.py", line 19, in <module>
    import paramiko
ImportError: No module named paramiko

重新安装依赖还是不行sudo pip3 install -r requirements.txt --upgrade
Requirement already up-to-date: cryptography in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.7)
Requirement already up-to-date: enum34 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (1.1.6)
Requirement already up-to-date: frida-tools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (2.0.2)
Requirement already up-to-date: idna in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (2.8)
Requirement already up-to-date: ipaddress in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (1.0.22)
Requirement already up-to-date: paramiko in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (2.6.0)
Requirement already up-to-date: prompt-toolkit in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (2.0.9)
Requirement already up-to-date: pyasn1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (0.4.6)
Requirement already up-to-date: pycparser in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (2.19)
Requirement already up-to-date: Pygments in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (2.4.2)
Requirement already up-to-date: PyNaCl in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (1.3.0)
Requirement already up-to-date: scp in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 16)) (0.13.2)
Requirement already up-to-date: six in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 17)) (1.12.0)
Requirement already up-to-date: tqdm in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 18)) (4.32.2)
Requirement already up-to-date: wcwidth in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 19)) (0.1.7)
Requirement already satisfied, skipping upgrade: frida<13.0.0,>=12.5.9 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from frida-tools->-r requirements.txt (line 7)) (12.6.11)

**Comment by andermoran** [comment]
Run
`sudo pip install paramiko`

**Comment by XLsn0w** [comment]
> Run
> `sudo pip install paramiko`

yes , I do it, But it's still a hint,  ImportError: No module named paramiko,  Do you have any other ideas

**Comment by PeipeiQ** [comment]
I also have this problem. Anyone have idea?

**Comment by andermoran** [comment]
> > Run
> > `sudo pip install paramiko`
> 
> yes , I do it, But it's still a hint, ImportError: No module named paramiko, Do you have any other ideas

In your log you use pip3, are you sure you're using pip without the 3? Run dump.py with python2.7
`python2.7 dump.py` as this may be related to python3. dump.py was written in python 2 not python 3 so try running `sudo pip install -r requirements.txt --upgrade` as well. If that does not work then run `sudo pip2.7 install -r requirements.txt --upgrade`

**Comment by XLsn0w** [comment]
> sudo pip2.7 install paramiko

sudo pip2.7 install paramiko, sudo pip2.7 install scp, sudo pip2.7 install tqdm  ,   then $ dump.py -l,  The list appears successfully, Thank you very much
