### ISSUE TITLE
"failed to get the task for process" with checkra1n 0.9.3 and iOS 13.2.2

### ISSUE THREAD

**Issue by tmm1** [AloneMonkey/frida-ios-dump#87]
```
Start the target app com.example.app
failed to get the task for process 651
```

**Comment by tmm1** [comment]
My bad, I forgot to install frida server as outlined in https://www.frida.re/docs/ios/

**Comment by NeoVilsonWong** [comment]
https://build.frida.re 403 forbiden


> My bad, I forgot to install frida server as outlined in https://www.frida.re/docs/ios/
