### ISSUE TITLE
Exception: Error reading SSH protocol banner[Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by LiuSky** [AloneMonkey/frida-ios-dump#92]
<img width="993" alt="截屏2019-12-18上午11 36 12" src="https://user-images.githubusercontent.com/3087745/71053878-f3efbd80-218a-11ea-8e31-500bcdf5e688.png">
@AloneMonkey 由于对py不熟，所以想请帮忙看下是什么问题

**Comment by fanyuexiang** [comment]
1. if you use python3 ---> branch 3x. otherwise,use branch master
2.you should login your  jailbreak device by OpenSSH first If you've never logged in
3.If you have changed your OpenSSH password, edit it in dump.py file

**Comment by LiuSky** [comment]
thank you @fanyuexiang
